import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import path from "path";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "realestate-tracker",
  description: "Generated by create next app",
  icons: [path.join(__dirname, "public/favicon.png")],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <link rel="icon" href="/favicon.png" sizes="any" />

      <body className={inter.className}>
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider></body>
    </html>
  );
}
